# Generated by Django 4.2.1 on 2023-05-31 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_m7', '0002_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core_m7.estado', verbose_name='Estado'),
        ),
    ]
