# Generated by Django 4.2.1 on 2023-05-31 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_m7', '0003_alter_pedido_id_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='id_pedido',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_m7.estado', verbose_name='Estado'),
        ),
    ]
