# Generated by Django 4.2.1 on 2023-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_m7', '0004_remove_detalle_id_pedido_alter_pedido_id_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_estado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10),
        ),
    ]
