# Generated by Django 4.2.1 on 2023-05-31 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_m7', '0006_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_detalle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core_m7.detalle', verbose_name='Detalle'),
        ),
    ]
