# Generated by Django 4.2.1 on 2023-05-31 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_m7', '0008_remove_pedido_id_detalle_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detalle',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core_m7.detalle', verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
